### ISSUE TITLE
An acme.json with multiple certificates results in error.

### ISSUE THREAD

**Issue by davidjmeier** [koshatul/traefik-acme#13]
I'm running `traefik-acme` in a container against an `acme.json` file that has 2 domains.  While attempting to extract the cert/key for one of the domains I end up with the message `certificate resolver not found`.  I've validated the container can read `acme.json` and the domain is present.

To debug I spun the container up interactively and overrode the `entrypoint`.  The debug flag doesn't appear to give additional insight.

If there's anything additional to check please let me know.

Thank you!

**Comment by davidjmeier** [comment]
Closing the issue as I noticed my resolver name was different and needed to be passed (`-r`).

**Comment by koshatul** [comment]
Good to hear it's working.

There isn't a lot of debug, it's mostly for use during development, I should probably hide the option from the argument list.

**Comment by tikoflano** [comment]
The option `--certificate-resolver "myresolver"` should be added to the README

**Comment by koshatul** [comment]
Updated the README
