### ISSUE TITLE
Add support for Traefik v2

### ISSUE THREAD

**Issue by je-s** [koshatul/traefik-acme#14]
Hello,

I wanted to ask what you think about adding support for Traefik v2.
`traefik-acme` doesn't work for Traefik v2, because the structure of the `acme.json` changed slightly from Traefik v1 to v2.

I guess it should only be a matter of how the JSON get's parsed in the end.
The only difference is that a block gets wrapped into a "[resolver](https://doc.traefik.io/traefik/https/acme/#the-different-acme-challenges)"-property (`myresolver` in this case below), and the capitalisation of the properties in `Certificates` changed to lowercase.

Have a look at those two examples:
    - [Traefik v1 acme.json](https://github.com/traefik/traefik-migration-tool/blob/9a21a1ef41ef4860d6bd97abfceacb70547d248c/acme/fixtures/acme.json)
    - [Traefik v2 acme.json](https://github.com/traefik/traefik-migration-tool/blob/9a21a1ef41ef4860d6bd97abfceacb70547d248c/acme/fixtures/new-acme.json)

I guess the following would be sufficient:
&nbsp;&nbsp;&nbsp;&nbsp;1. Add a command line parameter for switching between the Traefik versions (e.g. `--traefik-version <v1 || v2>`)
&nbsp;&nbsp;&nbsp;&nbsp;2. Add a Traefik v2 specific command line parameter for specifying the "resolver" (e.g. `--resolver-name <resolver>`)
&nbsp;&nbsp;&nbsp;&nbsp;3. Adjust the parsing of the JSON based on 1. and 2.

If you need help, just let me know and I'll happily support you with that and leave you an PR.

Best regards,
JE

**Comment by koshatul** [comment]
The latest version should work with both, it [tries](https://github.com/koshatul/traefik-acme/blob/master/traefik/store.go#L46) `v2` syntax and falls back to `v1`, the only requirement is that a `certificate-resolver` is specified (if it's not the default "[acme](https://github.com/koshatul/traefik-acme/blob/master/cmd/traefik-acme/main.go#L44)" ):

I added some specific testing against those two sources, and it works.

version 1 command:
```shell
traefik-acme --acme="test/issue-14/v1/acme.json" --cert "cert.pem" --key "key.pem" "test.example.com"
```

version 2 command:
```shell
traefik-acme --acme="test/issue-14/v2/new-acme.json" --certificate-resolver "myresolver" --cert "cert.pem" --key "key.pem" "test.example.com"
```

**Comment by koshatul** [comment]
Give me a heads up if it doesn't work for you.
