### ISSUE TITLE
Thanks! - Built docker image please?

### ISSUE THREAD

**Issue by doug62** [koshatul/traefik-acme#3]
Thanks for offering up this excellent utility - I'm unfamiliar with linux/go development and unable to build - would be nice if a docker image of this was avail so we could mount that and use the utility.  Excellent work tho!

**Comment by koshatul** [comment]
Added a docker build to the deploy and instructions in the README.md.

But this should work.

```shell
docker run --rm \
 -v "/docker/traefik/config/:/config" \
 --workdir /config \
 koshatul/traefik-acme:latest domain.example.com
```
