### ISSUE TITLE
Problem extracting wilcard domains

### ISSUE THREAD

**Issue by mefernandez** [koshatul/traefik-acme#5]
Hi!

I've tried to extract certs from `acme.json` using this tool but it shows this message: 

```
docker run --rm  \
-v "/input/:/input"  \
-v "/tmp/certs:/output"  \
--workdir /output  \
koshatul/traefik-acme:latest --acme "/input/acme.json" -d '*.mydomain.com'

time="2020-07-08T10:16:40Z" level=info msg="certificate not found for *.mydomain.com"
```

`acme.json` excerpt (traefik v2.2):

```json
...
 "Certificates": [
      {
        "domain": {
          "main": "*.mydomain.com"
        },
        "certificate": "...
```

Cheers.

Mariano.

**Comment by koshatul** [comment]
I think the issue might be the "certificate resolver" name, the original code assumes it's set to just `acme`.

```json
{
    "acme": {
        "Account": { ... },
        "Certificates": [ ... ]
    }
}
```

If that is set to anything else it won't find it, I've modified the program to look for `acme` by default, but using `--certificate-resolver "foo"` that can be changed, there's a PR in progress, once it's merged I'll tag a new version and that should work once you put the certificate resolver name into the command.
