### ISSUE TITLE
Possible error in docker example in readme

### ISSUE THREAD

**Issue by Kolossi** [koshatul/traefik-acme#52]
First, great util, exactly what I was after.

I used the docker form in readme.md, but for me the example docker command didn't work, I needed to add additional params:

```
...
koshatul/traefik-acme:latest --acme "/input/acme.json" domain.example.com \
-c /output/cert.pem -k /output/key.pem
```

Without this, debug output reported writing the files to "cert.pem" and "key.pem" they weren't in output directory.

After this fix, debug output reported writing them to "/output/cert.pem" and "/output/key.pem" and there they were.

Hope that helps, thanks again for a great util.

**Comment by koshatul** [comment]
I tested it and it seems to work from the example, did you have the `--workdir /output` in the docker command ?

**Comment by koshatul** [comment]
I added a test into the regression test list, seems to work as per the README.

```shell
$ docker run --rm -v "/home/runner/work/traefik-acme/traefik-acme/test/issue-52:/input" -v "/home/runner/work/traefik-acme/traefik-acme/artifacts/test/issue-52:/output" --workdir /output koshatul/traefik-acme:latest --acme "/input/acme.json" test.example.com | tee "artifacts/test/issue-52/cert.pem.log"
Unable to find image 'koshatul/traefik-acme:latest' locally
latest: Pulling from koshatul/traefik-acme
365c89c6eef7: Pulling fs layer
365c89c6eef7: Verifying Checksum
365c89c6eef7: Download complete
365c89c6eef7: Pull complete
Digest: sha256:b8782c2c6ba13cfdc3bd9afb7a20263bba27e3c1d4049c338678fb2e0db1b869
Status: Downloaded newer image for koshatul/traefik-acme:latest
time="2021-12-13T04:12:49Z" level=info msg="Successfully wrote test.example.com certificate (cert.pem) and key (key.pem)"
$ grep "^Certificate" "artifacts/test/issue-52/cert.pem"
Certificate
```

**Comment by Kolossi** [comment]
I could have sworn I added --workdir, but it's been a while and I can't find the command in my history.  I've also changed my setup quite a bit, and can't rerun a test right now.

So I'd say the extra test is a great addition, fine with closing down this issue.

Thanks again for the great tool, which after I finish the reconfig of my system, I will be using regularly!

**Comment by koshatul** [comment]
All good, if it does it again re-open the issue or create a new one, but I'm marking this one as done :)
